/*在这里定义常量，只是为了方便统一*/

const EVENT_SEND_INDEX1 = 'INDEX1';
const EVENT_SEND_INDEX2 = 'INDEX2';
const EVENT_SEND_INDEX3 = 'INDEX3';
const EVENT_SEND_INDEX4 = 'INDEX4';

module.exports = {
    EVENT_SEND_INDEX1: EVENT_SEND_INDEX1,
    EVENT_SEND_INDEX2: EVENT_SEND_INDEX2,
    EVENT_SEND_INDEX3: EVENT_SEND_INDEX3,
    EVENT_SEND_INDEX4: EVENT_SEND_INDEX4,
}